name: Auto Cert Manager

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  ALI_KEY: ${{ secrets.ALI_KEY }}
  ALI_SECRET: ${{ secrets.ALI_SECRET }}
  CF_KEY: ${{ secrets.CF_KEY }}
  CF_EMAIL: ${{ secrets.CF_EMAIL }}
  CERT_DIR: "${{ github.workspace }}/certs"
  ZIP_PASSWORD: ${{ secrets.MYCERT_PWD }}

jobs:
  cert-manager:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y certbot openssl zip unzip
        pip install --upgrade certbot certbot-dns-aliyun certbot-dns-cloudflare

    - name: Commit Changes
      run: |
        touch certs/test.txt
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add "$CERT_DIR"/
        git commit -m "Auto-renew certificates $(date +'%Y-%m-%d %H:%M:%S')"
        git push
