name: Auto Cert Manager

on:
  schedule:
    - cron: '0 0 * * *' # 每日UTC 0点（北京时间8点）
  workflow_dispatch: # 手动触发

env:
  ALI_KEY: ${{ secrets.ALI_KEY }}
  ALI_SECRET: ${{ secrets.ALI_SECRET }}
  CF_KEY: ${{ secrets.CF_KEY }}
  CF_EMAIL: ${{ secrets.CF_EMAIL }}
  CERT_DIR: "./certs"
  ZIP_PASSWORD: ${{ secrets.MYCERT_PWD }}

jobs:
  cert-manager:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y certbot openssl zip unzip
        pip install certbot-dns-aliyun certbot-dns-cloudflare

